name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
        msystem: MINGW64

    - name: Verify GCC installation
      run: gcc --version
      shell: msys2 {0}

    - name: Verify CMake installation
      run: cmake --version
      shell: msys2 {0}

    - name: Configure CMake
      run: cmake -S . -B build -G "MinGW Makefiles"
      shell: msys2 {0}

    - name: Build
      run: cmake --build build
      shell: msys2 {0}

    - name: Run tests
      run: ctest --test-dir build
      shell: msys2 {0}
