name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup_environment:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true # 确保检查出子模块

    - name: Cache MSYS2
      id: cache-msys2
      uses: actions/cache@v4
      with:
        path: C:\tools\msys64
        key: msys2-v3

    - name: Setup MSYS2
      if: steps.cache-msys2.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v4
      with:
        install: >
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
        msystem: MINGW64

    - name: Verify GCC installation
      run: gcc --version
      shell: msys2 {0}

    - name: Verify CMake installation
      run: cmake --version
      shell: msys2 {0}

  build:
    runs-on: windows-latest
    needs: setup_environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true # 确保检查出子模块

    - name: Cache MSYS2
      uses: actions/cache@v4
      with:
        path: C:\tools\msys64
        key: msys2-v3

    - name: Setup MSYS2
      if: steps.cache-msys2.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v4
      with:
        install: >
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
        msystem: MINGW64

    - name: Configure CMake
      run: cmake -S . -B build -G "MinGW Makefiles"
      shell: msys2 {0}

    - name: Build
      run: cmake --build build
      shell: msys2 {0}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build

  run_tests:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true # 确保检查出子模块

    - name: Cache MSYS2
      uses: actions/cache@v4
      with:
        path: C:\tools\msys64
        key: msys2-v3

    - name: Setup MSYS2
      if: steps.cache-msys2.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v4
      with:
        install: >
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
        msystem: MINGW64

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build

    - name: Run tests
      run: ctest --test-dir build
      shell: msys2 {0}
